# Generated by Django 5.1.2 on 2024-10-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_employee_options_alter_employee_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
