# Generated by Django 5.1.2 on 2024-10-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clockrecord_comment_inventoryitem_todo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('superAdmin', 'Super Admin'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
